[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sesc-auth-sdk"
version = "2.0.8"
description = "SDK for authentification into SESC IT Team services for SESC"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.5",
    "fastapi>=0.135.1",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.13.1",
    "pyjwt[crypto]>=2.12.1",
    "python-jose[cryptography]>=3.5.0",
]

[dependency-groups]
dev = [
    "pyrefly>=1.1.1",
]
